# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=128)),
                ('shop_name', models.CharField(max_length=255)),
                ('scopes', models.TextField()),
            ],
        ),
    ]
